// Generated by scripts/generate-release-history.py. Do not edit by hand.

extension ReleaseHistoryCatalog {
    static let generatedEntries: [ReleaseHistoryEntry] = [
        ReleaseHistoryEntry(
            version: "1.7.6",
            date: "May 25, 2026",
            headline: "替换了原有的系统图标，为Cursor、Windsurf、Trae、Qoder等Git工作区源添加了专属的自定义logo资源，更新了相关的数据模型和视图显示逻辑。",
            changes: [
                "新增GitWorkspaceSourceID枚举与相关工具类，支持Claude、Codex、Cursor等多源配置",
                "新增偏好设置项gitWorkspaceSourceIDs，可自定义启用的仓库数据来源",
                "在设置界面添加仓库源配置卡片，支持切换会话来源和编辑器工作区来源",
                "重构Git活动视图，改用配置的源ID过滤会话和工作区数据",
                "新增完整的测试用例覆盖源解析、工作区路径读取等逻辑",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.7.5",
            date: "May 25, 2026",
            headline: "新增GitDiff交互点击测试模块与配套测试",
            changes: [
                "新增diff文本测量、概览布局计算模块",
                "新增侧边概览栏显示差异块",
                "重构渲染调色板支持选中状态样式",
                "重构diff布局计算支持自适应容器宽度",
                "新增代码行自动换行适配窄宽度",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.7.4",
            date: "May 24, 2026",
            headline: "新增了完整的Sparkle增量更新自动化流程，包括delta生成、签名和appcast更新；同时扩展了调试符号清理脚本，新增对对象文件和CMake构建产物的清理，并在代码签名脚本中跳过这些无用工件；新增了对应的单元测试，完善了CI发布流程的注释与步骤调整。",
            changes: [
                "新增了完整的Sparkle增量更新自动化流程，包括delta生成、签名和appcast更新；同时扩展了调试符号清理脚本，新增对对象文件和CMake构建产物的清理，并在代码签名脚本中跳过这些无用工件；新增了对应的单元测试，完善了CI发布流程的注释与步骤调整。",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.7.3",
            date: "May 24, 2026",
            headline: "添加llama.cpp子模块与相关桥接代码",
            changes: [
                "新增本地AI设置页面与语义搜索功能",
                "仅支持Apple Silicon Mac，更新构建与发布脚本",
                "新增嵌入模型管理与会话相似性搜索",
                "优化构建流程，添加代码签名与瘦身脚本",
                "移除TranscriptAnalysisService内的本地TF-IDF分析器实例，改为通过索引获取持久化快照",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.7.2",
            date: "May 24, 2026",
            headline: "新增了完整的技术术语词典系统，包括词典模型、标准化处理、设置页面，实现了基于词典的会话术语分析，并且当词典变更时会自动触发会话分析重新生成。",
            changes: [
                "这一提交实现了多项 Claude 用量限制相关的功能改进：",
                "新增可配置的 Claude 用量窗口显示功能，支持在设置中选择额外显示的 Claude 计划用量行",
                "改进用量文本解析器，支持非断字符格式的时间和标签匹配",
                "优化缓存写入逻辑，合并新旧快照数据以保留完整用量信息",
                "重构用量窗口目录管理，统一窗口ID、排序和过滤逻辑",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.7.1",
            date: "May 23, 2026",
            headline: "本次提交新增了OpenComputerUseKit第三方库作为桌面自动化依赖，重构了Claude桌面使用采集流程：",
            changes: [
                "新增屏幕录制权限检查器，统一管理屏幕录制权限请求逻辑",
                "新增OpenComputerUse原生文本阅读器，优先使用自动化接口采集数据",
                "重构使用解析逻辑，支持新的Claude桌面UI用量格式",
                "新增自动化测试用例覆盖新功能",
                "修复权限重检查逻辑，支持屏幕录制权限的重新校验",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.7.0",
            date: "May 23, 2026",
            headline: "新增DashboardModelTable组件，实现多提供商模型使用数据表格展示",
            changes: [
                "新增DashboardModelKey和DashboardModelUsage类型，支持多模型身份标识与使用统计",
                "重构DashboardView，支持切换显示Claude/OpenAI状态卡片，统一模型展示逻辑",
                "重构DashboardViewModel，实现全提供商会话聚合统计，新增多模型维度分析",
                "新增单元测试验证仪表盘聚合逻辑",
                "更新文档与文本适配多提供商场景",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.6.9",
            date: "May 22, 2026",
            headline: "新增了文档站点使用的社交预览图片资源",
            changes: [
                "替换了文档目录下assets/screens中的所有演示截图，为文档展示提供最新的界面效果",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.6.8",
            date: "May 22, 2026",
            headline: "新增LinuxDo图标资源文件及Contents.json配置",
            changes: [
                "为MainPage和SettingsSection添加assetName属性以获取对应logo名称",
                "修改SidebarRow组件，支持显示自定义资产图片替代系统图标",
                "在侧边栏和设置侧边栏中为LinuxDo项添加logo展示",
                "调整了截图表格的表头结构，将原本的行内标题改为表头形式，并且将分享统计导出的演示图折叠进详情块中，优化文档排版可读性",
                "将原来的单张截图排版改为表格布局，让截图更整齐美观，同时更新了两个菜单面板的演示gif文件",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.6.7",
            date: "May 22, 2026",
            headline: "新增Linux.do论坛阅读导航的滞回切换逻辑，调整布局参数",
            changes: [
                "重构帖子跳转方法，支持按楼层号精准匹配而非流索引",
                "优化阅读位置记录防抖和滚动定位逻辑",
                "添加项目README的图标和资源目录说明",
                "更新了项目说明、功能特性、安装方式、隐私政策、构建指南、项目结构和贡献指南，新增LICENSE文件完整添加AGPLv3许可内容",
                "Pin Ghostty warning fixes",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.6.6",
            date: "May 22, 2026",
            headline: "新增prune-debug-symbols.sh脚本用于清理*.dSYM调试符号包",
            changes: [
                "在构建GitTools和Linguist运行时流程中加入符号清理步骤",
                "优化代码签名逻辑，增加失败重试机制",
                "修复验证脚本，排除dSYM目录并加入残留dSYM检查",
                "调整所有相关find命令以跳过dSYM目录",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.6.5",
            date: "May 22, 2026",
            headline: "实现了Linux Do帖子的阅读位置自动保存功能，新增侧边/底部阅读导航栏，支持继续阅读跳转",
            changes: [
                "本提交完整实现了Linux.do论坛的扩展内容支持：",
                "新增callout提示块、活动卡片、任务列表项等新内容模型",
                "支持高亮、键盘按键、上下标等内联格式",
                "完善引用块解析，支持Discourse侧边引用样式",
                "重构表格数据模型，添加列表项唯一标识",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.6.4",
            date: "May 21, 2026",
            headline: "新增基于本地使用统计数据生成的Token Town小镇游戏",
            changes: [
                "添加StatsPeriod的Codable支持以适配新功能",
                "在侧边栏和主页面中新增Token Town入口",
                "新增随机数生成、经济系统、状态存储等核心模块",
                "新增完整的测试用例覆盖核心功能逻辑",
                "新增SpriteKit渲染的小镇场景和交互视图",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.6.3",
            date: "May 21, 2026",
            headline: "重构屏幕样式解析逻辑，新增NotchIslandScreenStyleResolver统一处理有效样式计算",
            changes: [
                "传递屏幕ID而非仅本地化名称到AtollRuntimeBridge，优化屏幕匹配准确性",
                "修复两处传入screen.localizedName的调用，改为直接传入NSScreen对象",
                "新增测试用例验证样式解析逻辑正确性",
                "新增屏幕样式枚举，替换原有的单一外接显示器选择器",
                "支持为每个屏幕单独设置显示样式（贴合挖孔/浮动岛）",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.6.2",
            date: "May 21, 2026",
            headline: "新增LinuxDo话题路由解析与导航逻辑",
            changes: [
                "完善Post响应模型与LinuxDoPost数据结构",
                "实现完整的HTML内容解析与富文本展示",
                "添加话题列表页UI优化与分类颜色支持",
                "集成本地通知跳转处理",
                "新增帖子跳转加载逻辑与测试用例",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.6.1",
            date: "May 21, 2026",
            headline: "skip",
            changes: [
                "skip",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.6.0",
            date: "May 21, 2026",
            headline: "新增LocalSkillDetailModel和RemoteSkillDetailModel用于展示技能详情数据",
            changes: [
                "新增SkillFactModel、SkillMarkdownDocument等配套数据结构",
                "重构MainWindowModeShell的侧边栏切换逻辑，使用transition替代offset动画",
                "为SkillsStore添加selectedLocalDetail和selectedRemoteDetail计算属性",
                "新增对应测试用例验证详情数据正确性",
                "实现了LinuxDo侧边栏、工作区视图，将其加入主窗口导航系统，调整了主窗口布局适配新页面，修复了侧边栏切换偏移逻辑",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.5.13",
            date: "May 20, 2026",
            headline: "新增ClaudeCLIInstallDetecting协议与实现类，检测Claude CLI安装状态",
            changes: [
                "新增桌面辅助功能权限检查器，重构权限检测逻辑",
                "添加.permissionRecheck触发类型，支持权限重检查流程",
                "新增UsageLimitStore权限状态自动清理与权限重检查循环",
                "新增主窗口激活时自动触发权限重检查的逻辑",
                "重构ClaudeProvider的使用限额报告逻辑，根据CLI安装状态展示不同引导文案",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.5.12",
            date: "May 20, 2026",
            headline: "为各类使用统计数据模型添加数据修订ID，用于生成唯一缓存键，确保数据变更时正确刷新视图缓存。",
            changes: [
                "为TokenUsage、ModelUsage数组、TrendSeries添加dataRevisionID计算属性",
                "更新UsageModelBreakdownSnapshot和UsageTrendSnapshotKey，加入修订ID参数",
                "补充对应测试用例验证缓存键随数据变更而变化",
                "新增完整的AI配置浏览详情页，支持按分类查看配置文件",
                "新增侧边栏导航和搜索功能，支持筛选配置文件",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.5.11",
            date: "May 20, 2026",
            headline: "新增了Ops工具面板，聚焦Homebrew管理和开发环境检查，具体实现包括：",
            changes: [
                "新增AppEnvironment中的OpsStore依赖注入",
                "在侧边栏添加Ops导航入口",
                "实现完整的Ops侧边栏和详情视图",
                "新增命令行执行封装、数据模型和测试用例",
                "扩展主窗口布局支持Ops模式切换",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.5.10",
            date: "May 20, 2026",
            headline: "This commit adds full realtime leaderboard functionality:",
            changes: [
                "Adds CloudKit push notification entitlement and registration",
                "Implements subscription management for leaderboard realtime updates",
                "Adds local storage for realtime state tracking",
                "Adds view model integration for realtime status and auto-refresh",
                "Updates UI to show realtime sync status",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.5.9",
            date: "May 20, 2026",
            headline: "新增AppLanguagePreference管理应用语言偏好，支持跟随系统、英文、简体中文",
            changes: [
                "重构字体加载逻辑，根据语言自动切换Sora或系统字体",
                "全量替换硬编码字符串为本地化宏L10n",
                "新增本地化测试用例与InfoPlist多语言配置",
                "新增设置页面语言切换选项，支持重启后生效",
                "将项目中所有直接写死的文本替换为L10n本地化字符串宏，统一管理应用文案，方便后续多语言适配和修改，同时保持原有默认值保证功能正常运行。",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.5.8",
            date: "May 20, 2026",
            headline: "add UsageLimitSegmentLayout for usage segment calculation",
            changes: [
                "refactor UsageLimitWindowCard to use view model",
                "rewrite UsageLimitSegmentStrip with Canvas for better performance",
                "add new unit tests for layout logic",
                "add release history files for versions 1.4.3, 1.5.2~1.5.7",
                "update release workflow to handle new release note files",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.5.7",
            date: "May 20, 2026",
            headline: "同时在源仓库和公共附属仓库创建GitHub Release，补充说明源仓库的发布用于项目内部记录",
            changes: [
                "调整权限说明，明确内置GITHUB_TOKEN可完成源仓库发布",
                "在工作流中新增源仓库发布的步骤",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.5.6",
            date: "May 20, 2026",
            headline: "skip",
            changes: [
                "skip",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.5.5",
            date: "May 20, 2026",
            headline: "This commit adds a full suite of network debugging features:",
            changes: [
                "New network proxy event types and breakpoint management APIs",
                "Network body store for persisting request/response data",
                "Upstream environment and credential management with Keychain support",
                "Full request/response export/import support (cURL, HAR, raw formats)",
                "Replay, batch automate and WebSocket debugging workflows",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.5.4",
            date: "May 19, 2026",
            headline: "本次提交完成了多项核心功能更新：",
            changes: [
                "调整主窗口侧边栏与分区结构",
                "完善开发工具界面的交互与展示",
                "更新相关测试覆盖",
                "更新测试用例与发布历史版本号",
                "调整项目依赖与构建配置，移除废弃的脚本插件管理器代码",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.5.3",
            date: "May 19, 2026",
            headline: "此次提交包含维护更新：",
            changes: [
                "更新内部集成配置",
                "调整相关设置与测试覆盖",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.5.2",
            date: "May 19, 2026",
            headline: "新增被动刷新助手状态的API，无需主动请求即可获取当前注册状态",
            changes: [
                "新增check类型的助手操作枚举与对应展示文案",
                "优化release构建脚本，添加助手工具重签名和权限校验逻辑",
                "修复Xcode构建签名配置，禁用自动注入权限",
                "新增单元测试验证被动状态刷新逻辑",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.5.0 / 1.5.1",
            date: "May 19, 2026",
            headline: "重构并扩展了排行榜功能，新增了每日排行榜的日期导航控件，支持切换查看过往UTC日期的排行榜数据。",
            changes: [
                "将原收藏模型面板重命名为收藏模型面板并调整标题文本",
                "新增`LeaderboardDailyDateNavigator`工具类处理UTC日期计算和格式化",
                "新增每日周期选择控件，支持前后切换日期和显示今日/昨日标签",
                "重构排行榜总览面板布局，拆分周期选择器并集成日期导航控件",
                "更新视图模型和测试用例，支持按指定UTC日期加载排行榜数据",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.4.9",
            date: "May 18, 2026",
            headline: "实现首次启动时自动设置开机自启的默认行为，仅在用户未手动修改过设置时生效",
            changes: [
                "新增了完整的悬浮面板服务状态展示体系：",
                "创建状态模型与适配器，支持Claude和OpenAI服务状态解析",
                "添加悬浮状态视图组件，支持状态展示与空状态、错误状态处理",
                "扩展悬浮面板状态与视图，支持展开/折叠状态切换",
                "新增从悬浮面板跳转主窗口指定页面的功能",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.4.8",
            date: "May 18, 2026",
            headline: "新增Atoll驱动的Mac动态岛功能，支持多屏幕、快捷开关与自定义模块",
            changes: [
                "添加设置页面与偏好设置支持，可配置显示模式、尺寸与启用模块",
                "新增版本历史页面，可查看1.4.0以来的更新日志",
                "添加Atoll子模块依赖与所需的权限配置",
                "新增相关单元测试与UI预览代码",
                "为git工作区卡片视图设置全局的leading对齐方式，统一卡片布局的对齐表现",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.4.7",
            date: "May 18, 2026",
            headline: "Network debugging and settings polish.",
            changes: [
                "Added the network debugging module.",
                "Added adjustable network traffic layout controls.",
                "Refined split-view behavior, updater state, and settings structure.",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.4.6",
            date: "May 18, 2026",
            headline: "Leaderboard sync, caching, and status monitoring.",
            changes: [
                "Added local leaderboard caching and sync support.",
                "Added leaderboard history sync and display.",
                "Added OpenAI and Codex service status monitoring.",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.4.5",
            date: "May 17, 2026",
            headline: "System monitor and richer leaderboard history.",
            changes: [
                "Added the system monitor feature.",
                "Added complete leaderboard history support.",
                "Refined leaderboard layout and component structure.",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.4.4",
            date: "May 17, 2026",
            headline: "App icon, status, and cost-estimation updates.",
            changes: [
                "Added new app icon assets and configuration.",
                "Added cost estimation mode and Claude status monitoring.",
                "Added long-context pricing support and improved activity analysis structure.",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.4.3",
            date: "May 17, 2026",
            headline: "skip",
            changes: [
                "skip",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.4.1 / 1.4.2",
            date: "May 17, 2026",
            headline: "CLI environment tools and provider switching.",
            changes: [
                "Added CLI environment detection and cleanup.",
                "Added API provider switching with configurable key storage.",
                "Rebuilt the activity page around the new main-window activity view.",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.4.0",
            date: "May 17, 2026",
            headline: "Terminal, Git stats, and release-readiness improvements.",
            changes: [
                "Added terminal support and Git language statistics.",
                "Added Git stats scope preferences and refreshed Git controls.",
                "Added the in-app update badge and cleaned up release pipeline dependencies.",
            ]
        ),
    ]
}
