// Generated by scripts/generate-release-history.py. Do not edit by hand.

extension ReleaseHistoryCatalog {
    static let generatedEntries: [ReleaseHistoryEntry] = [
        ReleaseHistoryEntry(
            version: "1.5.12",
            date: "May 20, 2026",
            headline: "为各类使用统计数据模型添加数据修订ID，用于生成唯一缓存键，确保数据变更时正确刷新视图缓存。",
            changes: [
                "为TokenUsage、ModelUsage数组、TrendSeries添加dataRevisionID计算属性",
                "更新UsageModelBreakdownSnapshot和UsageTrendSnapshotKey，加入修订ID参数",
                "补充对应测试用例验证缓存键随数据变更而变化",
                "新增完整的AI配置浏览详情页，支持按分类查看配置文件",
                "新增侧边栏导航和搜索功能，支持筛选配置文件",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.5.11",
            date: "May 20, 2026",
            headline: "新增了Ops工具面板，包含监听端口管理、进程监控、Homebrew管理、开发环境检查、系统清理和诊断功能，具体实现包括：",
            changes: [
                "新增AppEnvironment中的OpsStore依赖注入",
                "在侧边栏添加Ops导航入口",
                "实现完整的Ops侧边栏和详情视图",
                "新增命令行执行封装、数据模型和测试用例",
                "扩展主窗口布局支持Ops模式切换",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.5.10",
            date: "May 20, 2026",
            headline: "This commit adds full realtime leaderboard functionality:",
            changes: [
                "Adds CloudKit push notification entitlement and registration",
                "Implements subscription management for leaderboard realtime updates",
                "Adds local storage for realtime state tracking",
                "Adds view model integration for realtime status and auto-refresh",
                "Updates UI to show realtime sync status",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.5.9",
            date: "May 20, 2026",
            headline: "新增AppLanguagePreference管理应用语言偏好，支持跟随系统、英文、简体中文",
            changes: [
                "重构字体加载逻辑，根据语言自动切换Sora或系统字体",
                "全量替换硬编码字符串为本地化宏L10n",
                "新增本地化测试用例与InfoPlist多语言配置",
                "新增设置页面语言切换选项，支持重启后生效",
                "将项目中所有直接写死的文本替换为L10n本地化字符串宏，统一管理应用文案，方便后续多语言适配和修改，同时保持原有默认值保证功能正常运行。",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.5.8",
            date: "May 20, 2026",
            headline: "add UsageLimitSegmentLayout for usage segment calculation",
            changes: [
                "refactor UsageLimitWindowCard to use view model",
                "rewrite UsageLimitSegmentStrip with Canvas for better performance",
                "add new unit tests for layout logic",
                "add release history files for versions 1.4.3, 1.5.2~1.5.7",
                "update release workflow to handle new release note files",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.5.7",
            date: "May 20, 2026",
            headline: "同时在源仓库和公共附属仓库创建GitHub Release，补充说明源仓库的发布用于项目内部记录",
            changes: [
                "调整权限说明，明确内置GITHUB_TOKEN可完成源仓库发布",
                "在工作流中新增源仓库发布的步骤",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.5.6",
            date: "May 20, 2026",
            headline: "skip",
            changes: [
                "skip",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.5.5",
            date: "May 20, 2026",
            headline: "This commit adds a full suite of network debugging features:",
            changes: [
                "New network proxy event types and breakpoint management APIs",
                "Network body store for persisting request/response data",
                "Upstream environment and credential management with Keychain support",
                "Full request/response export/import support (cURL, HAR, raw formats)",
                "Replay, batch automate and WebSocket debugging workflows",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.5.4",
            date: "May 19, 2026",
            headline: "本次提交完成了多项核心功能更新：",
            changes: [
                "重构网络侧边栏与分区，新增代理、助手、上游代理三个分区，迁移旧版setup分区",
                "新增WebSocket帧捕获与展示、规则匹配元数据展示",
                "完善规则引擎与代理后端实现，支持规则增删改查、插件管理、断点调试、请求重放",
                "更新测试用例与发布历史版本号",
                "调整项目依赖与构建配置，移除废弃的脚本插件管理器代码",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.5.3",
            date: "May 19, 2026",
            headline: "此次提交新增了网络调试时的上游代理支持，包括：",
            changes: [
                "将Rockxy子模块切换至自定义分支仓库",
                "添加上游代理相关的数据模型、配置UI和偏好存储",
                "新增系统代理上游探测与自动链式代理功能",
                "在流量列表中显示当前请求使用的上游代理信息",
                "添加上游连通性测试功能",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.5.2",
            date: "May 19, 2026",
            headline: "新增被动刷新助手状态的API，无需主动请求即可获取当前注册状态",
            changes: [
                "新增check类型的助手操作枚举与对应展示文案",
                "优化release构建脚本，添加助手工具重签名和权限校验逻辑",
                "修复Xcode构建签名配置，禁用自动注入权限",
                "新增单元测试验证被动状态刷新逻辑",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.5.0 / 1.5.1",
            date: "May 19, 2026",
            headline: "重构并扩展了排行榜功能，新增了每日排行榜的日期导航控件，支持切换查看过往UTC日期的排行榜数据。",
            changes: [
                "将原收藏模型面板重命名为收藏模型面板并调整标题文本",
                "新增`LeaderboardDailyDateNavigator`工具类处理UTC日期计算和格式化",
                "新增每日周期选择控件，支持前后切换日期和显示今日/昨日标签",
                "重构排行榜总览面板布局，拆分周期选择器并集成日期导航控件",
                "更新视图模型和测试用例，支持按指定UTC日期加载排行榜数据",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.4.9",
            date: "May 18, 2026",
            headline: "实现首次启动时自动设置开机自启的默认行为，仅在用户未手动修改过设置时生效",
            changes: [
                "新增了完整的悬浮面板服务状态展示体系：",
                "创建状态模型与适配器，支持Claude和OpenAI服务状态解析",
                "添加悬浮状态视图组件，支持状态展示与空状态、错误状态处理",
                "扩展悬浮面板状态与视图，支持展开/折叠状态切换",
                "新增从悬浮面板跳转主窗口指定页面的功能",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.4.8",
            date: "May 18, 2026",
            headline: "新增Atoll驱动的Mac动态岛功能，支持多屏幕、快捷开关与自定义模块",
            changes: [
                "添加设置页面与偏好设置支持，可配置显示模式、尺寸与启用模块",
                "新增版本历史页面，可查看1.4.0以来的更新日志",
                "添加Atoll子模块依赖与所需的权限配置",
                "新增相关单元测试与UI预览代码",
                "为git工作区卡片视图设置全局的leading对齐方式，统一卡片布局的对齐表现",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.4.7",
            date: "May 18, 2026",
            headline: "Network debugging and settings polish.",
            changes: [
                "Added the network debugging module.",
                "Added adjustable network traffic layout controls.",
                "Refined split-view behavior, updater state, and settings structure.",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.4.6",
            date: "May 18, 2026",
            headline: "Leaderboard sync, caching, and status monitoring.",
            changes: [
                "Added local leaderboard caching and sync support.",
                "Added leaderboard history sync and display.",
                "Added OpenAI and Codex service status monitoring.",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.4.5",
            date: "May 17, 2026",
            headline: "System monitor and richer leaderboard history.",
            changes: [
                "Added the system monitor feature.",
                "Added complete leaderboard history support.",
                "Refined leaderboard layout and component structure.",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.4.4",
            date: "May 17, 2026",
            headline: "App icon, status, and cost-estimation updates.",
            changes: [
                "Added new app icon assets and configuration.",
                "Added cost estimation mode and Claude status monitoring.",
                "Added long-context pricing support and improved activity analysis structure.",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.4.3",
            date: "May 17, 2026",
            headline: "skip",
            changes: [
                "skip",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.4.1 / 1.4.2",
            date: "May 17, 2026",
            headline: "CLI environment tools and provider switching.",
            changes: [
                "Added CLI environment detection and cleanup.",
                "Added API provider switching with configurable key storage.",
                "Rebuilt the activity page around the new main-window activity view.",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.4.0",
            date: "May 17, 2026",
            headline: "Terminal, Git stats, and release-readiness improvements.",
            changes: [
                "Added terminal support and Git language statistics.",
                "Added Git stats scope preferences and refreshed Git controls.",
                "Added the in-app update badge and cleaned up release pipeline dependencies.",
            ]
        ),
    ]
}
