// Generated by scripts/generate-release-history.py. Do not edit by hand.

extension ReleaseHistoryCatalog {
    static let generatedEntries: [ReleaseHistoryEntry] = [
        ReleaseHistoryEntry(
            version: "1.4.9",
            date: "May 18, 2026",
            headline: "实现首次启动时自动设置开机自启的默认行为，仅在用户未手动修改过设置时生效",
            changes: [
                "新增了完整的悬浮面板服务状态展示体系：",
                "创建状态模型与适配器，支持Claude和OpenAI服务状态解析",
                "添加悬浮状态视图组件，支持状态展示与空状态、错误状态处理",
                "扩展悬浮面板状态与视图，支持展开/折叠状态切换",
                "新增从悬浮面板跳转主窗口指定页面的功能",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.4.8",
            date: "May 18, 2026",
            headline: "新增Atoll驱动的Mac动态岛功能，支持多屏幕、快捷开关与自定义模块",
            changes: [
                "添加设置页面与偏好设置支持，可配置显示模式、尺寸与启用模块",
                "新增版本历史页面，可查看1.4.0以来的更新日志",
                "添加Atoll子模块依赖与所需的权限配置",
                "新增相关单元测试与UI预览代码",
                "为git工作区卡片视图设置全局的leading对齐方式，统一卡片布局的对齐表现",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.4.7",
            date: "May 18, 2026",
            headline: "Network debugging and settings polish.",
            changes: [
                "Added the network debugging module.",
                "Added adjustable network traffic layout controls.",
                "Refined split-view behavior, updater state, and settings structure.",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.4.6",
            date: "May 18, 2026",
            headline: "Leaderboard sync, caching, and status monitoring.",
            changes: [
                "Added local leaderboard caching and sync support.",
                "Added leaderboard history sync and display.",
                "Added OpenAI and Codex service status monitoring.",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.4.5",
            date: "May 17, 2026",
            headline: "System monitor and richer leaderboard history.",
            changes: [
                "Added the system monitor feature.",
                "Added complete leaderboard history support.",
                "Refined leaderboard layout and component structure.",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.4.4",
            date: "May 17, 2026",
            headline: "App icon, status, and cost-estimation updates.",
            changes: [
                "Added new app icon assets and configuration.",
                "Added cost estimation mode and Claude status monitoring.",
                "Added long-context pricing support and improved activity analysis structure.",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.4.1 / 1.4.2",
            date: "May 17, 2026",
            headline: "CLI environment tools and provider switching.",
            changes: [
                "Added CLI environment detection and cleanup.",
                "Added API provider switching with configurable key storage.",
                "Rebuilt the activity page around the new main-window activity view.",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.4.0",
            date: "May 17, 2026",
            headline: "Terminal, Git stats, and release-readiness improvements.",
            changes: [
                "Added terminal support and Git language statistics.",
                "Added Git stats scope preferences and refreshed Git controls.",
                "Added the in-app update badge and cleaned up release pipeline dependencies.",
            ]
        ),
    ]
}
